name: Primeira pipeline Python

on:
  push:
    branches: [main]

env:
  PYTHONPATH: .

jobs:
  testesoma:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          
      - name: Instalar dependências
        run: pip install pytest

      - name: Executar teste de soma
        run: python -m pytest testPY/test_soma.py

  testesub:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install pytest

      - name: Executar teste de subtração
        run: python -m pytest testPY/test_sub.py

  testemult:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install pytest

      - name: Executar teste de multiplicação
        run: python -m pytest testPY/test_mult.py

  testediv:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install pytest

      - name: Executar teste de divisão
        run: python -m pytest testPY/test_div.py

  deploy:
    needs: [testesoma, testesub, testemult, testediv]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso!"